language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO="django>=1.4,<1.5", MPTT="django-mptt==0.5.5"
    - DJANGO="django>=1.5,<1.6", MPTT="django-mptt==0.6.0"    
install:
    - pip install $DJANGO django-shop $MPTT django-treeadmin django-easytests six
script:
    python develop.py test
notifications:
    email: false
